-- Generado desde database/parksmart_db.sql.
-- Sin credenciales ni clausulas DEFINER.

DROP VIEW IF EXISTS `vw_bitacoradetalle`;
CREATE OR REPLACE SQL SECURITY INVOKER VIEW `vw_bitacoradetalle` AS select `b`.`idBitacora` AS `idBitacora`,`b`.`modulo` AS `modulo`,`b`.`accion` AS `accion`,`b`.`descripcion` AS `descripcion`,`b`.`resultado` AS `resultado`,`b`.`direccionIp` AS `direccionIp`,`b`.`fechaRegistro` AS `fechaRegistro`,`u`.`idUsuario` AS `idUsuario`,`u`.`nombreUsuario` AS `nombreUsuario`,`r`.`idRol` AS `idRol`,`r`.`nombreRol` AS `nombreRol` from ((`bitacora` `b` left join `usuario` `u` on((`b`.`idUsuario` = `u`.`idUsuario`))) left join `rol` `r` on((`u`.`idRol` = `r`.`idRol`)));

DROP VIEW IF EXISTS `vw_clientesactivos`;
CREATE OR REPLACE SQL SECURITY INVOKER VIEW `vw_clientesactivos` AS select `c`.`idCliente` AS `idCliente`,`c`.`identificacion` AS `identificacion`,concat_ws(' ',`c`.`nombre`,`c`.`primerApellido`,`c`.`segundoApellido`) AS `nombreCompleto`,`c`.`telefono` AS `telefono`,`c`.`correoElectronico` AS `correoElectronico`,`c`.`estado` AS `estado`,`c`.`fechaCreacion` AS `fechaCreacion` from `cliente` `c` where (`c`.`estado` = 'ACTIVO');

DROP VIEW IF EXISTS `vw_deudaspendientes`;
CREATE OR REPLACE SQL SECURITY INVOKER VIEW `vw_deudaspendientes` AS select `d`.`idDeuda` AS `idDeuda`,`d`.`codigoDeuda` AS `codigoDeuda`,`d`.`montoDeuda` AS `montoDeuda`,`d`.`fechaGeneracion` AS `fechaGeneracion`,`d`.`fechaLimite` AS `fechaLimite`,`d`.`estado` AS `estadoDeuda`,`p`.`idPago` AS `idPago`,`p`.`codigoPago` AS `codigoPago`,`p`.`montoTotal` AS `montoTotal`,`p`.`estado` AS `estadoPago`,`c`.`idCliente` AS `idCliente`,concat_ws(' ',`c`.`nombre`,`c`.`primerApellido`,`c`.`segundoApellido`) AS `nombreCliente`,`c`.`telefono` AS `telefono`,`c`.`correoElectronico` AS `correoElectronico`,`v`.`placa` AS `placa` from (((((`deuda` `d` join `pago` `p` on((`d`.`idPago` = `p`.`idPago`))) join `ocupacion` `o` on((`p`.`idOcupacion` = `o`.`idOcupacion`))) join `reserva` `r` on((`o`.`idReserva` = `r`.`idReserva`))) join `cliente` `c` on((`r`.`idCliente` = `c`.`idCliente`))) join `vehiculo` `v` on((`r`.`idVehiculo` = `v`.`idVehiculo`))) where (`d`.`estado` in ('PENDIENTE','VENCIDA'));

DROP VIEW IF EXISTS `vw_espaciosdisponibles`;
CREATE OR REPLACE SQL SECURITY INVOKER VIEW `vw_espaciosdisponibles` AS select `e`.`idEspacio` AS `idEspacio`,`e`.`codigoEspacio` AS `codigoEspacio`,`e`.`tipoEspacio` AS `tipoEspacio`,`e`.`estado` AS `estadoEspacio`,`s`.`idSector` AS `idSector`,`s`.`nombreSector` AS `nombreSector`,`s`.`ubicacion` AS `ubicacion`,`s`.`estado` AS `estadoSector` from (`espacio` `e` join `sector` `s` on((`e`.`idSector` = `s`.`idSector`))) where ((`e`.`estado` = 'DISPONIBLE') and (`s`.`estado` = 'ACTIVO'));

DROP VIEW IF EXISTS `vw_notificacionespendientes`;
CREATE OR REPLACE SQL SECURITY INVOKER VIEW `vw_notificacionespendientes` AS select `n`.`idNotificacion` AS `idNotificacion`,`n`.`tipoNotificacion` AS `tipoNotificacion`,`n`.`canal` AS `canal`,`n`.`titulo` AS `titulo`,`n`.`mensaje` AS `mensaje`,`n`.`destinatario` AS `destinatario`,`n`.`estado` AS `estado`,`n`.`fechaCreacion` AS `fechaCreacion`,`c`.`idCliente` AS `idCliente`,concat_ws(' ',`c`.`nombre`,`c`.`primerApellido`,`c`.`segundoApellido`) AS `nombreCliente` from (`notificacion` `n` join `cliente` `c` on((`n`.`idCliente` = `c`.`idCliente`))) where (`n`.`estado` = 'PENDIENTE');

DROP VIEW IF EXISTS `vw_ocupacionesactivas`;
CREATE OR REPLACE SQL SECURITY INVOKER VIEW `vw_ocupacionesactivas` AS select `o`.`idOcupacion` AS `idOcupacion`,`o`.`fechaEntrada` AS `fechaEntrada`,`o`.`fechaSalida` AS `fechaSalida`,`o`.`estado` AS `estadoOcupacion`,`r`.`idReserva` AS `idReserva`,`r`.`codigoReserva` AS `codigoReserva`,`c`.`idCliente` AS `idCliente`,concat_ws(' ',`c`.`nombre`,`c`.`primerApellido`,`c`.`segundoApellido`) AS `nombreCliente`,`v`.`idVehiculo` AS `idVehiculo`,`v`.`placa` AS `placa`,`v`.`tipoVehiculo` AS `tipoVehiculo`,`e`.`idEspacio` AS `idEspacio`,`e`.`codigoEspacio` AS `codigoEspacio`,`s`.`nombreSector` AS `nombreSector` from (((((`ocupacion` `o` join `reserva` `r` on((`o`.`idReserva` = `r`.`idReserva`))) join `cliente` `c` on((`r`.`idCliente` = `c`.`idCliente`))) join `vehiculo` `v` on((`r`.`idVehiculo` = `v`.`idVehiculo`))) join `espacio` `e` on((`r`.`idEspacio` = `e`.`idEspacio`))) join `sector` `s` on((`e`.`idSector` = `s`.`idSector`))) where (`o`.`estado` = 'EN_CURSO');

DROP VIEW IF EXISTS `vw_pagospendientes`;
CREATE OR REPLACE SQL SECURITY INVOKER VIEW `vw_pagospendientes` AS select `p`.`idPago` AS `idPago`,`p`.`codigoPago` AS `codigoPago`,`p`.`tiempoCobradoMinutos` AS `tiempoCobradoMinutos`,`p`.`tarifaPorHora` AS `tarifaPorHora`,`p`.`montoSubtotal` AS `montoSubtotal`,`p`.`montoImpuesto` AS `montoImpuesto`,`p`.`montoTotal` AS `montoTotal`,`p`.`estado` AS `estadoPago`,`p`.`fechaLimitePago` AS `fechaLimitePago`,`o`.`idOcupacion` AS `idOcupacion`,`r`.`idReserva` AS `idReserva`,`r`.`codigoReserva` AS `codigoReserva`,`c`.`idCliente` AS `idCliente`,concat_ws(' ',`c`.`nombre`,`c`.`primerApellido`,`c`.`segundoApellido`) AS `nombreCliente`,`c`.`telefono` AS `telefono`,`c`.`correoElectronico` AS `correoElectronico`,`v`.`placa` AS `placa` from ((((`pago` `p` join `ocupacion` `o` on((`p`.`idOcupacion` = `o`.`idOcupacion`))) join `reserva` `r` on((`o`.`idReserva` = `r`.`idReserva`))) join `cliente` `c` on((`r`.`idCliente` = `c`.`idCliente`))) join `vehiculo` `v` on((`r`.`idVehiculo` = `v`.`idVehiculo`))) where (`p`.`estado` = 'PENDIENTE');

DROP VIEW IF EXISTS `vw_qractivos`;
CREATE OR REPLACE SQL SECURITY INVOKER VIEW `vw_qractivos` AS select `q`.`idQr` AS `idQr`,`q`.`codigoQr` AS `codigoQr`,`q`.`fechaGeneracion` AS `fechaGeneracion`,`q`.`fechaActivacion` AS `fechaActivacion`,`q`.`fechaExpiracion` AS `fechaExpiracion`,`q`.`estado` AS `estadoQr`,`r`.`idReserva` AS `idReserva`,`r`.`codigoReserva` AS `codigoReserva`,`c`.`idCliente` AS `idCliente`,concat_ws(' ',`c`.`nombre`,`c`.`primerApellido`,`c`.`segundoApellido`) AS `nombreCliente`,`v`.`placa` AS `placa` from (((`qr` `q` join `reserva` `r` on((`q`.`idReserva` = `r`.`idReserva`))) join `cliente` `c` on((`r`.`idCliente` = `c`.`idCliente`))) join `vehiculo` `v` on((`r`.`idVehiculo` = `v`.`idVehiculo`))) where (`q`.`estado` in ('GENERADO','ACTIVO'));

DROP VIEW IF EXISTS `vw_reservasactivas`;
CREATE OR REPLACE SQL SECURITY INVOKER VIEW `vw_reservasactivas` AS select `r`.`idReserva` AS `idReserva`,`r`.`codigoReserva` AS `codigoReserva`,`r`.`fechaInicioReserva` AS `fechaInicioReserva`,`r`.`fechaFinReserva` AS `fechaFinReserva`,`r`.`estado` AS `estadoReserva`,`c`.`idCliente` AS `idCliente`,concat_ws(' ',`c`.`nombre`,`c`.`primerApellido`,`c`.`segundoApellido`) AS `nombreCliente`,`v`.`placa` AS `placa`,`e`.`codigoEspacio` AS `codigoEspacio`,`s`.`nombreSector` AS `nombreSector` from ((((`reserva` `r` join `cliente` `c` on((`r`.`idCliente` = `c`.`idCliente`))) join `vehiculo` `v` on((`r`.`idVehiculo` = `v`.`idVehiculo`))) join `espacio` `e` on((`r`.`idEspacio` = `e`.`idEspacio`))) join `sector` `s` on((`e`.`idSector` = `s`.`idSector`))) where (`r`.`estado` in ('PENDIENTE','CONFIRMADA'));

DROP VIEW IF EXISTS `vw_reservasdetalle`;
CREATE OR REPLACE SQL SECURITY INVOKER VIEW `vw_reservasdetalle` AS select `r`.`idReserva` AS `idReserva`,`r`.`codigoReserva` AS `codigoReserva`,`r`.`fechaInicioReserva` AS `fechaInicioReserva`,`r`.`fechaFinReserva` AS `fechaFinReserva`,`r`.`estado` AS `estadoReserva`,`c`.`idCliente` AS `idCliente`,concat_ws(' ',`c`.`nombre`,`c`.`primerApellido`,`c`.`segundoApellido`) AS `nombreCliente`,`c`.`telefono` AS `telefono`,`c`.`correoElectronico` AS `correoElectronico`,`v`.`idVehiculo` AS `idVehiculo`,`v`.`placa` AS `placa`,`v`.`marca` AS `marca`,`v`.`modelo` AS `modelo`,`v`.`color` AS `color`,`v`.`tipoVehiculo` AS `tipoVehiculo`,`e`.`idEspacio` AS `idEspacio`,`e`.`codigoEspacio` AS `codigoEspacio`,`e`.`tipoEspacio` AS `tipoEspacio`,`e`.`estado` AS `estadoEspacio`,`s`.`idSector` AS `idSector`,`s`.`nombreSector` AS `nombreSector` from ((((`reserva` `r` join `cliente` `c` on((`r`.`idCliente` = `c`.`idCliente`))) join `vehiculo` `v` on((`r`.`idVehiculo` = `v`.`idVehiculo`))) join `espacio` `e` on((`r`.`idEspacio` = `e`.`idEspacio`))) join `sector` `s` on((`e`.`idSector` = `s`.`idSector`)));
