"""crear esquema base

Revision ID: 38f1b9784628
Revises: 
Create Date: 2026-08-03 17:32:32.503348

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '38f1b9784628'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cliente',
    sa.Column('idCliente', mysql.BIGINT(unsigned=True), autoincrement=True, nullable=False),
    sa.Column('identificacion', sa.String(length=20), nullable=False),
    sa.Column('nombre', sa.String(length=50), nullable=False),
    sa.Column('primerApellido', sa.String(length=50), nullable=False),
    sa.Column('segundoApellido', sa.String(length=50), nullable=True),
    sa.Column('telefono', sa.String(length=20), nullable=False),
    sa.Column('correoElectronico', sa.String(length=120), nullable=False),
    sa.Column('direccion', sa.String(length=250), nullable=True),
    sa.Column('estado', sa.Enum('ACTIVO', 'INACTIVO', 'SUSPENDIDO'), server_default=sa.text("'ACTIVO'"), nullable=False),
    sa.Column('fechaCreacion', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('fechaActualizacion', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('provincia', sa.String(length=50), nullable=True),
    sa.Column('canton', sa.String(length=50), nullable=True),
    sa.Column('distrito', sa.String(length=50), nullable=True),
    sa.Column('direccionExacta', sa.String(length=250), nullable=True),
    sa.PrimaryKeyConstraint('idCliente')
    )
    op.create_index('IX_Cliente_PrimerApellido', 'cliente', ['primerApellido'], unique=False)
    op.create_index('IX_Cliente_Telefono', 'cliente', ['telefono'], unique=False)
    op.create_index('UK_Cliente_CorreoElectronico', 'cliente', ['correoElectronico'], unique=True)
    op.create_index('UK_Cliente_Identificacion', 'cliente', ['identificacion'], unique=True)
    op.create_table('rol',
    sa.Column('idRol', mysql.BIGINT(unsigned=True), autoincrement=True, nullable=False),
    sa.Column('nombreRol', sa.String(length=50), nullable=False),
    sa.Column('descripcion', sa.String(length=250), nullable=True),
    sa.Column('estado', sa.Enum('ACTIVO', 'INACTIVO'), server_default=sa.text("'ACTIVO'"), nullable=False),
    sa.Column('fechaCreacion', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('fechaActualizacion', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'), nullable=False),
    sa.PrimaryKeyConstraint('idRol')
    )
    op.create_index('IX_Rol_Estado', 'rol', ['estado'], unique=False)
    op.create_index('UK_Rol_NombreRol', 'rol', ['nombreRol'], unique=True)
    op.create_table('sector',
    sa.Column('idSector', mysql.BIGINT(unsigned=True), autoincrement=True, nullable=False),
    sa.Column('nombreSector', sa.String(length=50), nullable=False),
    sa.Column('descripcion', sa.String(length=250), nullable=True),
    sa.Column('ubicacion', sa.String(length=100), nullable=True),
    sa.Column('estado', sa.Enum('ACTIVO', 'INACTIVO', 'MANTENIMIENTO'), server_default=sa.text("'ACTIVO'"), nullable=False),
    sa.Column('fechaCreacion', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('fechaActualizacion', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'), nullable=False),
    sa.PrimaryKeyConstraint('idSector')
    )
    op.create_index('IX_Sector_Estado', 'sector', ['estado'], unique=False)
    op.create_index('UK_Sector_NombreSector', 'sector', ['nombreSector'], unique=True)
    op.create_table('espacio',
    sa.Column('idEspacio', mysql.BIGINT(unsigned=True), autoincrement=True, nullable=False),
    sa.Column('idSector', mysql.BIGINT(unsigned=True), nullable=False),
    sa.Column('codigoEspacio', sa.String(length=20), nullable=False),
    sa.Column('tipoEspacio', sa.Enum('REGULAR', 'MOTOCICLETA', 'DISCAPACIDAD', 'ELECTRICO', 'VIP'), server_default=sa.text("'REGULAR'"), nullable=False),
    sa.Column('estado', sa.Enum('DISPONIBLE', 'OCUPADO', 'RESERVADO', 'MANTENIMIENTO', 'INACTIVO'), server_default=sa.text("'DISPONIBLE'"), nullable=False),
    sa.Column('descripcion', sa.String(length=250), nullable=True),
    sa.Column('fechaCreacion', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('fechaActualizacion', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['idSector'], ['sector.idSector'], name='FK_Espacio_Sector', onupdate='CASCADE', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('idEspacio')
    )
    op.create_index('IX_Espacio_Estado', 'espacio', ['estado'], unique=False)
    op.create_index('IX_Espacio_IdSector', 'espacio', ['idSector'], unique=False)
    op.create_index('IX_Espacio_TipoEspacio', 'espacio', ['tipoEspacio'], unique=False)
    op.create_index('UK_Espacio_CodigoEspacio', 'espacio', ['codigoEspacio'], unique=True)
    op.create_table('usuario',
    sa.Column('idUsuario', mysql.BIGINT(unsigned=True), autoincrement=True, nullable=False),
    sa.Column('idRol', mysql.BIGINT(unsigned=True), nullable=False),
    sa.Column('idCliente', mysql.BIGINT(unsigned=True), nullable=True),
    sa.Column('nombreUsuario', sa.String(length=50), nullable=False),
    sa.Column('correoElectronico', sa.String(length=120), nullable=False),
    sa.Column('contrasenaHash', sa.String(length=255), nullable=False),
    sa.Column('estado', sa.Enum('ACTIVO', 'INACTIVO', 'BLOQUEADO'), server_default=sa.text("'ACTIVO'"), nullable=False),
    sa.Column('ultimoAcceso', sa.DateTime(), nullable=True),
    sa.Column('fechaCreacion', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('fechaActualizacion', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['idCliente'], ['cliente.idCliente'], name='FK_Usuario_Cliente', onupdate='CASCADE', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['idRol'], ['rol.idRol'], name='FK_Usuario_Rol', onupdate='CASCADE', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('idUsuario')
    )
    op.create_index('IX_Usuario_Estado', 'usuario', ['estado'], unique=False)
    op.create_index('IX_Usuario_IdCliente', 'usuario', ['idCliente'], unique=False)
    op.create_index('IX_Usuario_IdRol', 'usuario', ['idRol'], unique=False)
    op.create_index('IX_Usuario_UltimoAcceso', 'usuario', ['ultimoAcceso'], unique=False)
    op.create_index('UK_Usuario_CorreoElectronico', 'usuario', ['correoElectronico'], unique=True)
    op.create_index('UK_Usuario_NombreUsuario', 'usuario', ['nombreUsuario'], unique=True)
    op.create_table('vehiculo',
    sa.Column('idVehiculo', mysql.BIGINT(unsigned=True), autoincrement=True, nullable=False),
    sa.Column('idCliente', mysql.BIGINT(unsigned=True), nullable=False),
    sa.Column('placa', sa.String(length=20), nullable=False),
    sa.Column('marca', sa.String(length=50), nullable=True),
    sa.Column('modelo', sa.String(length=50), nullable=True),
    sa.Column('color', sa.String(length=30), nullable=True),
    sa.Column('tipoVehiculo', sa.Enum('AUTOMOVIL', 'MOTOCICLETA', 'CAMIONETA', 'OTRO'), server_default=sa.text("'AUTOMOVIL'"), nullable=False),
    sa.Column('estado', sa.Enum('ACTIVO', 'INACTIVO'), server_default=sa.text("'ACTIVO'"), nullable=False),
    sa.Column('fechaCreacion', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('fechaActualizacion', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['idCliente'], ['cliente.idCliente'], name='FK_Vehiculo_Cliente', onupdate='CASCADE', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('idVehiculo')
    )
    op.create_index('IX_Vehiculo_Estado', 'vehiculo', ['estado'], unique=False)
    op.create_index('IX_Vehiculo_IdCliente', 'vehiculo', ['idCliente'], unique=False)
    op.create_index('IX_Vehiculo_TipoVehiculo', 'vehiculo', ['tipoVehiculo'], unique=False)
    op.create_index('UK_Vehiculo_Placa', 'vehiculo', ['placa'], unique=True)
    op.create_table('bitacora',
    sa.Column('idBitacora', mysql.BIGINT(unsigned=True), autoincrement=True, nullable=False),
    sa.Column('idUsuario', mysql.BIGINT(unsigned=True), nullable=True),
    sa.Column('modulo', sa.String(length=50), nullable=False),
    sa.Column('accion', sa.String(length=100), nullable=False),
    sa.Column('descripcion', sa.String(length=500), nullable=True),
    sa.Column('resultado', sa.Enum('EXITOSO', 'FALLIDO', 'ADVERTENCIA'), server_default=sa.text("'EXITOSO'"), nullable=False),
    sa.Column('direccionIp', sa.String(length=45), nullable=True),
    sa.Column('userAgent', sa.String(length=250), nullable=True),
    sa.Column('fechaRegistro', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['idUsuario'], ['usuario.idUsuario'], name='FK_Bitacora_Usuario', onupdate='CASCADE', ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('idBitacora')
    )
    op.create_index('IX_Bitacora_Accion', 'bitacora', ['accion'], unique=False)
    op.create_index('IX_Bitacora_FechaRegistro', 'bitacora', ['fechaRegistro'], unique=False)
    op.create_index('IX_Bitacora_IdUsuario', 'bitacora', ['idUsuario'], unique=False)
    op.create_index('IX_Bitacora_Modulo', 'bitacora', ['modulo'], unique=False)
    op.create_index('IX_Bitacora_Resultado', 'bitacora', ['resultado'], unique=False)
    op.create_table('reserva',
    sa.Column('idReserva', mysql.BIGINT(unsigned=True), autoincrement=True, nullable=False),
    sa.Column('idCliente', mysql.BIGINT(unsigned=True), nullable=False),
    sa.Column('idVehiculo', mysql.BIGINT(unsigned=True), nullable=False),
    sa.Column('idEspacio', mysql.BIGINT(unsigned=True), nullable=False),
    sa.Column('codigoReserva', sa.String(length=30), nullable=False),
    sa.Column('fechaInicioReserva', sa.DateTime(), nullable=False),
    sa.Column('fechaFinReserva', sa.DateTime(), nullable=False),
    sa.Column('estado', sa.Enum('PENDIENTE', 'CONFIRMADA', 'CANCELADA', 'VENCIDA', 'UTILIZADA'), server_default=sa.text("'PENDIENTE'"), nullable=False),
    sa.Column('observaciones', sa.String(length=250), nullable=True),
    sa.Column('fechaCreacion', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('fechaActualizacion', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'), nullable=False),
    sa.CheckConstraint('fechaFinReserva > fechaInicioReserva', name='CK_Reserva_Fechas'),
    sa.ForeignKeyConstraint(['idCliente'], ['cliente.idCliente'], name='FK_Reserva_Cliente', onupdate='CASCADE', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['idEspacio'], ['espacio.idEspacio'], name='FK_Reserva_Espacio', onupdate='CASCADE', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['idVehiculo'], ['vehiculo.idVehiculo'], name='FK_Reserva_Vehiculo', onupdate='CASCADE', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('idReserva')
    )
    op.create_index('IX_Reserva_Estado', 'reserva', ['estado'], unique=False)
    op.create_index('IX_Reserva_Fechas', 'reserva', ['fechaInicioReserva', 'fechaFinReserva'], unique=False)
    op.create_index('IX_Reserva_IdCliente', 'reserva', ['idCliente'], unique=False)
    op.create_index('IX_Reserva_IdEspacio', 'reserva', ['idEspacio'], unique=False)
    op.create_index('IX_Reserva_IdVehiculo', 'reserva', ['idVehiculo'], unique=False)
    op.create_index('UK_Reserva_CodigoReserva', 'reserva', ['codigoReserva'], unique=True)
    op.create_table('qr',
    sa.Column('idQr', mysql.BIGINT(unsigned=True), autoincrement=True, nullable=False),
    sa.Column('idReserva', mysql.BIGINT(unsigned=True), nullable=False),
    sa.Column('codigoQr', sa.String(length=100), nullable=False),
    sa.Column('tokenQr', sa.String(length=250), nullable=True),
    sa.Column('fechaGeneracion', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('fechaValidezInicio', sa.DateTime(), nullable=True),
    sa.Column('fechaValidezFin', sa.DateTime(), nullable=True),
    sa.Column('fechaActivacion', sa.DateTime(), nullable=True),
    sa.Column('fechaExpiracion', sa.DateTime(), nullable=True),
    sa.Column('fechaUso', sa.DateTime(), nullable=True),
    sa.Column('estado', sa.Enum('GENERADO', 'ACTIVO', 'USADO', 'VENCIDO', 'CANCELADO'), server_default=sa.text("'GENERADO'"), nullable=False),
    sa.Column('fechaCreacion', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('fechaActualizacion', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'), nullable=False),
    sa.CheckConstraint('fechaExpiracion > fechaActivacion', name='CK_Qr_Fechas'),
    sa.ForeignKeyConstraint(['idReserva'], ['reserva.idReserva'], name='FK_Qr_Reserva', onupdate='CASCADE', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('idQr')
    )
    op.create_index('IX_Qr_Estado', 'qr', ['estado'], unique=False)
    op.create_index('IX_Qr_Fechas', 'qr', ['fechaActivacion', 'fechaExpiracion'], unique=False)
    op.create_index('UK_Qr_CodigoQr', 'qr', ['codigoQr'], unique=True)
    op.create_index('UK_Qr_IdReserva', 'qr', ['idReserva'], unique=True)
    op.create_table('ocupacion',
    sa.Column('idOcupacion', mysql.BIGINT(unsigned=True), autoincrement=True, nullable=False),
    sa.Column('idReserva', mysql.BIGINT(unsigned=True), nullable=False),
    sa.Column('idEspacio', mysql.BIGINT(unsigned=True), nullable=True),
    sa.Column('idQr', mysql.BIGINT(unsigned=True), nullable=True),
    sa.Column('fechaEntrada', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('fechaSalida', sa.DateTime(), nullable=True),
    sa.Column('tiempoTotalMinutos', mysql.INTEGER(unsigned=True), nullable=True),
    sa.Column('estado', sa.Enum('EN_CURSO', 'FINALIZADA', 'CANCELADA'), server_default=sa.text("'EN_CURSO'"), nullable=False),
    sa.Column('observaciones', sa.String(length=250), nullable=True),
    sa.Column('fechaCreacion', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('fechaActualizacion', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'), nullable=False),
    sa.CheckConstraint('fechaSalida IS NULL OR fechaSalida > fechaEntrada', name='CK_Ocupacion_Fechas'),
    sa.ForeignKeyConstraint(['idQr'], ['qr.idQr'], name='FK_Ocupacion_Qr', onupdate='CASCADE', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['idReserva'], ['reserva.idReserva'], name='FK_Ocupacion_Reserva', onupdate='CASCADE', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('idOcupacion')
    )
    op.create_index('IX_Ocupacion_Estado', 'ocupacion', ['estado'], unique=False)
    op.create_index('IX_Ocupacion_FechaEntrada', 'ocupacion', ['fechaEntrada'], unique=False)
    op.create_index('IX_Ocupacion_FechaSalida', 'ocupacion', ['fechaSalida'], unique=False)
    op.create_index('UK_Ocupacion_IdQr', 'ocupacion', ['idQr'], unique=True)
    op.create_index('UK_Ocupacion_IdReserva', 'ocupacion', ['idReserva'], unique=True)
    op.create_table('pago',
    sa.Column('idPago', mysql.BIGINT(unsigned=True), autoincrement=True, nullable=False),
    sa.Column('idOcupacion', mysql.BIGINT(unsigned=True), nullable=False),
    sa.Column('codigoPago', sa.String(length=30), nullable=False),
    sa.Column('tiempoCobradoMinutos', mysql.INTEGER(unsigned=True), server_default=sa.text('1'), nullable=True),
    sa.Column('tarifaPorHora', mysql.DECIMAL(precision=10, scale=2), server_default=sa.text("'0.00'"), nullable=True),
    sa.Column('montoSubtotal', mysql.DECIMAL(precision=10, scale=2), server_default=sa.text("'0.00'"), nullable=True),
    sa.Column('montoImpuesto', mysql.DECIMAL(precision=10, scale=2), server_default=sa.text("'0.00'"), nullable=False),
    sa.Column('montoTotal', mysql.DECIMAL(precision=10, scale=2), nullable=False),
    sa.Column('metodoPago', sa.Enum('EFECTIVO', 'TARJETA', 'SINPE', 'PASARELA'), nullable=True),
    sa.Column('estado', sa.Enum('PENDIENTE', 'PAGADO', 'RECHAZADO', 'VENCIDO', 'ANULADO'), server_default=sa.text("'PENDIENTE'"), nullable=False),
    sa.Column('fechaGeneracion', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('fechaLimitePago', sa.DateTime(), nullable=True),
    sa.Column('fechaPago', sa.DateTime(), nullable=True),
    sa.Column('referenciaTransaccion', sa.String(length=100), nullable=True),
    sa.Column('numeroComprobante', sa.String(length=100), nullable=True),
    sa.Column('observaciones', sa.String(length=250), nullable=True),
    sa.Column('fechaCreacion', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('fechaActualizacion', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'), nullable=False),
    sa.CheckConstraint('montoImpuesto >= 0', name='CK_Pago_MontoImpuesto'),
    sa.CheckConstraint('montoSubtotal >= 0', name='CK_Pago_MontoSubtotal'),
    sa.CheckConstraint('montoTotal >= 0', name='CK_Pago_MontoTotal'),
    sa.CheckConstraint('tarifaPorHora >= 0', name='CK_Pago_TarifaPorHora'),
    sa.CheckConstraint('tiempoCobradoMinutos > 0', name='CK_Pago_TiempoCobrado'),
    sa.ForeignKeyConstraint(['idOcupacion'], ['ocupacion.idOcupacion'], name='FK_Pago_Ocupacion', onupdate='CASCADE', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('idPago')
    )
    op.create_index('IX_Pago_Estado', 'pago', ['estado'], unique=False)
    op.create_index('IX_Pago_FechaLimitePago', 'pago', ['fechaLimitePago'], unique=False)
    op.create_index('IX_Pago_FechaPago', 'pago', ['fechaPago'], unique=False)
    op.create_index('IX_Pago_MetodoPago', 'pago', ['metodoPago'], unique=False)
    op.create_index('UK_Pago_CodigoPago', 'pago', ['codigoPago'], unique=True)
    op.create_index('UK_Pago_IdOcupacion', 'pago', ['idOcupacion'], unique=True)
    op.create_table('deuda',
    sa.Column('idDeuda', mysql.BIGINT(unsigned=True), autoincrement=True, nullable=False),
    sa.Column('idPago', mysql.BIGINT(unsigned=True), nullable=False),
    sa.Column('codigoDeuda', sa.String(length=30), nullable=False),
    sa.Column('montoDeuda', mysql.DECIMAL(precision=10, scale=2), nullable=False),
    sa.Column('fechaGeneracion', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('fechaLimite', sa.DateTime(), nullable=False),
    sa.Column('estado', sa.Enum('PENDIENTE', 'PAGADA', 'VENCIDA', 'ANULADA'), server_default=sa.text("'PENDIENTE'"), nullable=False),
    sa.Column('observaciones', sa.String(length=250), nullable=True),
    sa.Column('fechaCreacion', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('fechaActualizacion', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'), nullable=False),
    sa.CheckConstraint('montoDeuda >= 0', name='CK_Deuda_Monto'),
    sa.ForeignKeyConstraint(['idPago'], ['pago.idPago'], name='FK_Deuda_Pago', onupdate='CASCADE', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('idDeuda')
    )
    op.create_index('IX_Deuda_Estado', 'deuda', ['estado'], unique=False)
    op.create_index('IX_Deuda_FechaLimite', 'deuda', ['fechaLimite'], unique=False)
    op.create_index('UK_Deuda_CodigoDeuda', 'deuda', ['codigoDeuda'], unique=True)
    op.create_index('UK_Deuda_IdPago', 'deuda', ['idPago'], unique=True)
    op.create_table('notificacion',
    sa.Column('idNotificacion', mysql.BIGINT(unsigned=True), autoincrement=True, nullable=False),
    sa.Column('idCliente', mysql.BIGINT(unsigned=True), nullable=False),
    sa.Column('idReserva', mysql.BIGINT(unsigned=True), nullable=True),
    sa.Column('idPago', mysql.BIGINT(unsigned=True), nullable=True),
    sa.Column('idDeuda', mysql.BIGINT(unsigned=True), nullable=True),
    sa.Column('tipoNotificacion', sa.Enum('RESERVA', 'PAGO', 'DEUDA', 'SISTEMA'), nullable=False),
    sa.Column('canal', sa.Enum('EMAIL', 'SMS', 'WHATSAPP', 'PUSH'), server_default=sa.text("'EMAIL'"), nullable=False),
    sa.Column('titulo', sa.String(length=100), nullable=False),
    sa.Column('mensaje', sa.String(length=500), nullable=False),
    sa.Column('destinatario', sa.String(length=150), nullable=True),
    sa.Column('estado', sa.Enum('PENDIENTE', 'ENVIADA', 'LEIDA', 'ERROR'), server_default=sa.text("'PENDIENTE'"), nullable=False),
    sa.Column('fechaEnvio', sa.DateTime(), nullable=True),
    sa.Column('fechaLectura', sa.DateTime(), nullable=True),
    sa.Column('observaciones', sa.String(length=250), nullable=True),
    sa.Column('fechaCreacion', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('fechaActualizacion', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['idCliente'], ['cliente.idCliente'], name='FK_Notificacion_Cliente', onupdate='CASCADE', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['idPago'], ['pago.idPago'], name='FK_Notificacion_Pago', onupdate='CASCADE', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['idReserva'], ['reserva.idReserva'], name='FK_Notificacion_Reserva', onupdate='CASCADE', ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('idNotificacion')
    )
   
    
    op.create_index('IX_Notificacion_Canal', 'notificacion', ['canal'], unique=False)
    op.create_index('IX_Notificacion_Estado', 'notificacion', ['estado'], unique=False)
    op.create_index('IX_Notificacion_FechaEnvio', 'notificacion', ['fechaEnvio'], unique=False)
    op.create_index('IX_Notificacion_IdCliente', 'notificacion', ['idCliente'], unique=False)
    op.create_index('IX_Notificacion_Tipo', 'notificacion', ['tipoNotificacion'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
   
    
    op.drop_table('notificacion')
    op.drop_table('deuda')
    op.drop_table('pago')
    op.drop_table('ocupacion')
    op.drop_table('qr')
    op.drop_table('reserva')
    op.drop_table('bitacora')
    op.drop_table('vehiculo')
    op.drop_table('usuario')
    op.drop_table('espacio')
    op.drop_table('sector')
    op.drop_table('rol')
    op.drop_table('cliente')
    # ### end Alembic commands ###
